language: bash

services:
  - docker

env:
  - VERSION=3.4 VARIANT=bind
  - VERSION=3.4 VARIANT=geoip
  - VERSION=3.4 VARIANT=mysql
  - VERSION=3.4 VARIANT=oracle
  - VERSION=3.4 VARIANT=sqlite3

before_script:
  - export REPO=dockervan/powerdns
  - docker pull $REPO:$VERSION-$VARIANT || true

script:
  - cd $VERSION
  - docker build --pull -t powerdns $VARIANT

after_success:
  - docker tag powerdns $REPO:$VERSION-$VARIANT
  - if [ "$VERSION" == "3.4" ]; then docker tag $REPO:$VERSION-$VARIANT $REPO:3-$VARIANT; fi
  - if [ "$VERSION" == "3.4" ]; then docker tag $REPO:$VERSION-$VARIANT $REPO:$VARIANT; fi
  - docker images
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $REPO; fi
